name: debug-actions-secrets-if
'on':
  workflow_dispatch:
    inputs:
      env:
        description: "test inputs"
        required: true
        type: choice
        options:
          - stg
          - dev
          - sandbox

jobs:
  debug_actions:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
    env:
      ENV_TYPE: ${{ github.event.inputs.env }}
      ENV_TEST: ${{ secrets.SECRET_BOOLEAN }}
    steps:
      - name: name test ${{ github.event.inputs.env }} - ${{ env.ENV_TYPE }}
        run: echo 'start'
      - name: ENV_TEST true
        if: ${{ env.ENV_TEST == '1' }}
        run: echo 1 > _debug.log
      - name: ENV_TEST false
        if: ${{ env.ENV_TEST != '1' }}
        run: echo 0 > __debug.log
      - name: view log
        run: ls -la

      - if: ${{ env.ENV_TEST == '1' }}
        name: ENV_TEST 2 true
        run: echo 'ENV_TEST 2 true'
      - if: ${{ env.ENV_TEST != '1' }}
        name: ENV_TEST 2 false
        run: echo 'ENV_TEST 2 false'

      - run: echo 'end'

  debug_actions_2:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
    env:
      ENV_TYPE: ${{ github.event.inputs.env }}
      ENV_TEST: ${{ secrets.SECRET_BOOLEAN }}
    steps:
      - if: ${{ env.ENV_TEST == '1' }}
        name: Basic ${{ env.ENV_TYPE }} - Start Deploy
        uses: actions/checkout@v3
      - if: ${{ env.ENV_TEST == '1' }}
        name: Get npm cache directory path
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
