name: debug-actions-secrets-if
'on': workflow_dispatch
jobs:
  debug_actions:
    runs-on: ubuntu-latest
    env:
      ENV_TEST: secrets.SECRET_BOOLEAN
    steps:
      - run: echo 'start'
      - name: ENV_TEST true
        if: ${{ env.ENV_TEST == '1' }}
        run: echo 1
      - name: ENV_TEST false
        if: ${{ env.ENV_TEST != '1' }}
        run: echo 0
      - name: after if
        run: echo 'end'
