name: Debug Vars If
'on':
  workflow_dispatch:
    inputs:
      env:
        description: 'select type'
        required: true
        type: choice
        options:
          - sandbox
          - dev
          - stg

jobs:
  debug_vars_if:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
    steps:
      - if: ${{ vars.VARS_TEST == 'sandbox' }}
        name: Type sandbox : ${{ vars.VARS_TEST }}
        run: echo ${{ vars.VARS_TEST }}
      - if: ${{ vars.VARS_TEST == 'dev' }}
        name: Type dev : ${{ vars.VARS_TEST }}
        run: echo ${{ vars.VARS_TEST }}
      - if: ${{ vars.VARS_TEST == 'stg' }}
        name: Type stg : ${{ vars.VARS_TEST }}
        run: echo ${{ vars.VARS_TEST }}
