name: Debug Cache
'on':
  workflow_dispatch:

jobs:
  debug_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug 1
        run: |
          node -v
          npm -v
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Debug 2
        run: |
          node -v
          npm -v
          ls -la
        working-directory: workdir
