name: Debug Cache
'on':
  workflow_dispatch:

jobs:
  debug_cache:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workdir/debug-cache
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: workdir/debug-cache/package-lock.json

      - name: Node Modules Cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: workdir/debug-cache/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('workdir/debug-cache/package-lock.json') }}

      - name: Debug
        run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'

      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit == 'true' }}
        run: |
          ls -la
          echo 1

      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: |
          npm ci
          echo 0
