name: debug-actions-secrets-if
'on': workflow_dispatch
jobs:
  debug_actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test'
      - name: SECRET_BOOLEAN true
        if: ${{ secrets.SECRET_BOOLEAN == '1' }}
        run: echo 1
      - name: SECRET_BOOLEAN false
        if: ${{ secrets.SECRET_BOOLEAN != '1' }}
        run: echo 0
