name: debug-actions-secrets-if
'on': workflow_dispatch
jobs:
  debug_actions:
    runs-on: ubuntu-latest
    env:
      ENV_TEST: ${{ secrets.SECRET_BOOLEAN }}
    steps:
      - run: echo 'start'
      - name: ENV_TEST true
        if: ${{ env.ENV_TEST == '1' }}
        run: echo 1 > debug1.log
      - name: ENV_TEST false
        if: ${{ env.ENV_TEST != '1' }}
        run: echo 0 > debug2.log
      - name: view log
        run: ls -la
      - run: echo 'end'
